# Premier serveur
server {
	listen 127.0.0.1:8081;
    server_name localhost www.localhost;
    root /www;
    index index.htm index.html;
    client_max_body_size 1000000;

	server {
		listen 0.0.0.0:9090;
		server_name api.mysite.com;
		root /var/www/api;
		index index.py;
		client_max_body_size 500000;

		error_page 404 /errors/api-404.html;

		location / {
			root /var/www/api;
			index index.py;
			cgi_extension .py;
		}

		location /docs {
			root /var/www/api/docs;
			autoindex on;
		}
	}
}

